### ISSUE TITLE
paths broken in updated artic-2019-nf update

### ISSUE THREAD

**Issue by mcroxen** [phac-nml/resende-ncov2019#1]
With changes to the nextflow code it doesn't readily accept the 2kb_resende scheme

**Comment by Takadonet** [comment]
We move the scheme repo to https://github.com/phac-nml/ncov-schemes so it can more easily handle different schemes. Changes were reflect in latest commits [here](https://github.com/phac-nml/ncov2019-artic-nf/blob/master/conf/base.config#L15)

**Comment by DarianHole** [comment]
~~Changes to the [scheme repo](https://github.com/artic-network/primer-schemes) that the the Connor-lab pipeline is using changed an `_` to a `-` for the name of the `primer-schemes` directory so that seems to be the only thing that would need to be changed I believe~~

Changed repo name and the way they pull the repo in which is causing the issue

[connor-lab line](https://github.com/connor-lab/ncov2019-artic-nf/blob/e77feedba8ac34c526ed17bb3c111c88f9cb4c7d/conf/base.config#L18)
[scheme-repo](https://github.com/artic-network/primer-schemes)

~~We can pretty easily change that line in both the repos (as I think that is the only thing) but in the meantime I believe that passing the argument `--schemeDir primer_schemes` should work until that happens (probably tomorrow morning)~~

**Comment by DarianHole** [comment]
Ignore the above message, sorry. They changed the structure of the whole scheme repo and the download module (didn't check it till now). I will talkj with @Takadonet tomorrow to decide how to fix this repo or the https://github.com/phac-nml/ncov-schemes one as its going to take a bit more effort than I thought.

[new download module](https://github.com/connor-lab/ncov2019-artic-nf/blob/master/modules/artic.nf)
[old download module](https://github.com/phac-nml/ncov2019-artic-nf/blob/master/modules/artic.nf)

Darian

**Comment by DarianHole** [comment]
Hi @mcroxen this should be fixed in the https://github.com/phac-nml/primer-schemes repo now. It has all of the schemes in it so its a bit more flexible for future expansions (have to add Freed soon).

If it is not fixed and still causing issues open an issue on that one and I'll take a look at it again!

**Comment by mcroxen** [comment]
@DarianHole thanks. I was actually going to suggest hosting the Freed as well.

I get this new error (both with and without --schemeRepoURL)

`Missing output file(s) primer-schemes/nCoV-2019/2kb_resende/*.primer.bed`

I'm wondering if the following needs to be run on the scheme to generate the .primer.bed file

`https://github.com/artic-network/primer-schemes/blob/7d51020f7a4cf96d57d6aeb09bc4413e12ac9787/scripts/liftover.py`

**Comment by DarianHole** [comment]
Should be good now, missed that they added a new file (that is pretty much the same as the other files...) sorry about that! 

I'm just testing it now but so far it looks like its good

**Comment by mcroxen** [comment]
works for me locally as well. thanks so much!
